export const copy = {
  en: {
    common: {
      ai: "AI",
      antonyms: "Antonyms",
      close: "Close",
      dark: "Dark",
      definition: "Definition",
      english: "English",
      error: "Something went wrong",
      example: "Example",
      examples: "Examples",
      loading: "Loading...",
      light: "Light",
      large: "Large",
      media: "Pronunciation",
      medium: "Medium",
      openDetails: "Open details",
      pronunciation: "Pronunciation",
      recentlyViewed: "Recently viewed",
      removeFavorite: "Remove from favorites",
      saveFavorite: "Save to favorites",
      small: "Small",
      synonyms: "Synonyms",
      tryAgain: "Try again",
      uzbek: "Uzbek",
      wordOfDay: "Random word",
    },
    favorites: {
      clearAll: "Clear all",
      emptyDescription: "Tap the star on a result and it will appear here.",
      emptyTitle: "No favorites saved",
      items: (count) => `${count} saved ${count === 1 ? "word" : "words"}`,
      subtitle: "Your quick-access word list",
      title: "Favorites",
    },
    nav: {
      favorites: "Favorites",
      search: "Search",
      settings: "Settings",
    },
    search: {
      directionLabel: "Direction",
      historyTitle: "Search history",
      noResultsDescription: "Try another spelling or switch the EN/UZ direction.",
      noResultsTitle: "No results found",
      placeholder: "Search words",
      resultCount: (count) => `${count} matches`,
      resultsTitle: "Matches",
      searchingDescription:
        "Results appear after a short debounce for smoother typing.",
      searchingTitle: "Searching the dictionary...",
      subtitle: "Fast EN/UZ lookup",
      title: "Dictionary",
    },
    settings: {
      appLanguage: "App language",
      fontSize: "Font size",
      subtitle: "Language, theme, and app info",
      support: "Support project",
      theme: "Appearance",
      title: "Settings",
    },
    study: {
      answer: "Answer",
      answerRevealed: "Answer revealed",
      correct: "Correct",
      finalScore: (correct, total) => `${correct}/${total} correct`,
      finishedTitle: "Quiz finished",
      finishQuiz: "Finish",
      incorrect: "Not quite",
      nextQuestion: "Next question",
      progress: (current, total) => `Question ${current}/${total}`,
      questionCount: "Questions",
      revealAnswer: "Reveal answer",
      score: (correct, total) => `Score ${correct}/${total}`,
      selected: "Selected",
      startQuiz: "Start quiz",
      title: "Quiz mode",
      tryAgain: "Choose a length and start again.",
      wordBank: "Word bank",
    },
  },
  uz: {
    common: {
      ai: "AI",
      antonyms: "Antonimlar",
      close: "Yopish",
      dark: "Qorong'i",
      definition: "Ta'rif",
      english: "Inglizcha",
      error: "Nimadir xato ketdi",
      example: "Misol",
      examples: "Misollar",
      loading: "Yuklanmoqda...",
      light: "Yorug'",
      large: "Katta",
      media: "Talaffuz",
      medium: "O'rtacha",
      openDetails: "Batafsil ochish",
      pronunciation: "Talaffuz",
      recentlyViewed: "Yaqinda ko'rilganlar",
      removeFavorite: "Sevimlilardan olib tashlash",
      saveFavorite: "Sevimlilarga qo'shish",
      small: "Kichik",
      synonyms: "Sinonimlar",
      tryAgain: "Qayta urinib ko'rish",
      uzbek: "O'zbekcha",
      wordOfDay: "Tasodifiy so'z",
    },
    favorites: {
      clearAll: "Tozalash",
      emptyDescription:
        "Natijadagi yulduzchani bossangiz, so'z shu yerga saqlanadi.",
      emptyTitle: "Sevimlilar hali yo'q",
      items: (count) => `${count} ta saqlangan so'z`,
      subtitle: "Tez ochiladigan saqlangan so'zlar",
      title: "Sevimlilar",
    },
    nav: {
      favorites: "Sevimli",
      search: "Qidiruv",
      settings: "Sozlama",
    },
    search: {
      directionLabel: "Yo'nalish",
      historyTitle: "Qidiruv tarixi",
      noResultsDescription:
        "Boshqa yozilishini kiriting yoki EN/UZ yo'nalishini almashtiring.",
      noResultsTitle: "Natija topilmadi",
      placeholder: "So'z qidiring",
      resultCount: (count) => `${count} ta natija`,
      resultsTitle: "Topilganlar",
      searchingDescription:
        "Yozayotganingizda qidiruv silliq ishlashi uchun qisqa kutish ishlatiladi.",
      searchingTitle: "Lug'atdan qidirilmoqda...",
      subtitle: "Tezkor EN/UZ lug'at",
      title: "Lug'at",
    },
    settings: {
      appLanguage: "Ilova tili",
      fontSize: "Shrift o'lchami",
      subtitle: "Til, mavzu va ilova ma'lumoti",
      support: "Loyihani qo'llab-quvvatlash",
      theme: "Ko'rinish",
      title: "Sozlamalar",
    },
    study: {
      answer: "Javob",
      answerRevealed: "Javob ko'rsatildi",
      correct: "To'g'ri",
      finalScore: (correct, total) => `${correct}/${total} ta to'g'ri`,
      finishedTitle: "Test yakunlandi",
      finishQuiz: "Yakunlash",
      incorrect: "To'liq emas",
      nextQuestion: "Keyingi savol",
      progress: (current, total) => `${current}/${total}-savol`,
      questionCount: "Savollar soni",
      revealAnswer: "Javobni ko'rsatish",
      score: (correct, total) => `Hisob ${correct}/${total}`,
      selected: "Tanlandi",
      startQuiz: "Testni boshlash",
      title: "Quiz rejimi",
      tryAgain: "Savollar sonini tanlab, qayta boshlang.",
      wordBank: "So'zlar bazasi",
    },
  },
};
